version: '3.7' # version del docker-compose
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports: 
      - 33066:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret.root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel # red

  php: 
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: php 
    volumes:
      - ./:/var/www/html 
    ports:
      - 9000:80
    networks:
      - laravel # red

networks:
  laravel: